### ISSUE TITLE
google Maps navigation constrain

### ISSUE THREAD

**Issue by maojh** [codiceinutile/codiceinutile.org#10]
Penso che sia un dettaglio importante impostare i parametri per la cartina in modo da visualizzare bene la zona lombarda con i circoli attuali centrati, e limitare la navigazione in modo che ci si possa orientare ma non perdersi, magari toccando per sbaglio da mobile. Entrambe queste cose si fanno al volo modificando il json dell'api di google maps, questa settimana sono nel pieno degli esami e conto di farlo nei prossimi giorni. Scrivetemi qua sotto cosa ne pensate!

**Comment by federico-pepe** [comment]
Sul discorso della centratura ci avevo ragionato pure io quanto l'avevo inserita. Alla fine ha prevalso l'idea che essendo un progetto "nazionale" aveva più senso mettere il livello di zoom in modo che si vedesse l'intera penisola.

**Comment by maojh** [comment]
Dallo schermo del mio pc vedo dalla Bretagna alla Serbia mi sembra 
abbondante, l'idea di limitare la possibilità di perdersi, invece?

**Comment by federico-pepe** [comment]
Limitare le possibilità: per me ok purché l'Italia rimanga "navigabile".

Riesci a mettere lo screen di cosa vedi tu perché da Safari e Chrome su Mac la piantina è centrata su Roma.

![schermata 2017-02-23 alle 11 42 07](https://cloud.githubusercontent.com/assets/6317270/23255828/48b01782-f9bd-11e6-938f-a7c2736da325.png)
![schermata 2017-02-23 alle 11 42 14](https://cloud.githubusercontent.com/assets/6317270/23255829/48d63f16-f9bd-11e6-84c6-21a534e38e0a.png)

È chiaro che, purtroppo, per la forma dello stivale se zoomiamo di più perdiamo delle zone.

**Comment by maojh** [comment]
RIsulta anche a me centrato, lo zoom potrebbe anche andare bene, dico per essere sicuro che fosse quello che volevate
![screenshot from 2017-02-28 09-47-07](https://cloud.githubusercontent.com/assets/17848352/23398036/42a9a18c-fd9b-11e6-9794-fcc15492bb93.png)
