### ISSUE TITLE
Gallery home

### ISSUE THREAD

**Issue by maojh** [codiceinutile/codiceinutile.org#11]
Nella gallery con i testi, nella home sotto l'hero, i pulsanti non si vedono (essendoci i pallini sotto, servono?) e il gradiente scuro e i pallini di navigazione(ce n'è bisogno?) non sono responsive e copre il testo nella versione mobile.

**Comment by federico-pepe** [comment]
Confermo che bisogna sistemare alcune cose in ottica mobile-first. Assegno la cosa a @cybermarinella ma, ovviamente, se qualcuno vuole mettersi ben venga.
